export const CARDS_MMC_MDC = [
  { id: 1,  a: 'M(3)', b: '{0, 3, 6, 9, 12, 15, ...}' },
  { id: 2,  a: 'D(36)', b: '{1, 2, 3, 4, 6, 9, 12, 18, 36}' },
  { id: 3,  a: 'Número divisível por outro', b: 'Resto da divisão igual a zero' },
  { id: 4,  a: 'Critério de divisibilidade por 2', b: 'Termina em 0, 2, 4, 6 ou 8' },
  { id: 5,  a: 'Critério de divisibilidade por 5', b: 'Termina em 0 ou 5' },
  { id: 6,  a: 'Critério de divisibilidade por 10', b: 'Termina em 0' },
  { id: 7,  a: 'Número primo', b: 'Tem somente dois divisores: 1 e ele mesmo' },
  { id: 8,  a: 'Número composto', b: 'Tem mais de dois divisores' },
  { id: 9,  a: '0 é múltiplo de...', b: 'Todo número' },
  { id: 10, a: '1 é divisor de...', b: 'Todo número' },
  { id: 11, a: 'Todo número é múltiplo...', b: 'De si mesmo' },
  { id: 12, a: 'Todo número é divisor...', b: 'De si mesmo' },
  { id: 13, a: 'MMC', b: 'Menor múltiplo comum diferente de zero' },
  { id: 14, a: 'MDC', b: 'Maior divisor comum entre números' },
  { id: 15, a: 'MMC(6, 8)', b: '24' },
  { id: 16, a: 'MMC(20, 16)', b: '80' },
  { id: 17, a: 'MMC(15, 20, 36)', b: '180' },
  { id: 18, a: 'MDC(8, 18)', b: '2' },
  { id: 19, a: 'MDC(6, 18)', b: '6' },
  { id: 20, a: 'Ano bissexto', b: 'Ano divisível por 4' },
  { id: 21, a: 'Problemas de encontro', b: 'Costumam usar MMC' },
  { id: 22, a: 'Problemas de empacotamento', b: 'Costumam usar MDC' },
  { id: 23, a: 'Algoritmo de Euclides', b: 'Usa divisões sucessivas para achar o MDC' },
  { id: 24, a: 'Números coprimos', b: 'Têm MDC igual a 1' },
  { id: 25, a: 'Fatoração simultânea', b: 'Pode ser usada para calcular MMC e MDC' }
];
